In [4]:
from io import BytesIO
import pandas
import requests

In [5]:
url = "https://dart.fss.or.kr/pdf/download/excel.do?rcp_no=20220516000897&dcm_no=8662711&lang=ko"

In [12]:
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
resp = requests.get(url, headers = {"user-agent": user_agent})

In [22]:
table = BytesIO(resp.content)

pandas.read_excel(table)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,문서정보,NaN,NaN,NaN,NaN,NaN
1,보고서 유형 : 1분기보고서,정정공시여부 : 아니오,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN
4,문서작성일 : 2021-05-03,비교표시 재무제표 작성여부 : 예,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
62,재무상태표,유동/비유동법,NaN,NaN,NaN,NaN
63,포괄손익계산서,손익/기타포괄손익 개별작성,NaN,NaN,NaN,NaN
64,NaN,비용의 기능,NaN,NaN,NaN,NaN
65,NaN,세전기타포괄손익,NaN,NaN,NaN,NaN
66,현금흐름표,간접법,NaN,NaN,NaN,NaN